import uuid
import enum
from datetime import datetime
from typing import Optional, List
from sqlalchemy import String, Text, DateTime, ForeignKey, Enum as SQLEnum, Index, func, text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from pgvector.sqlalchemy import Vector

from app.core.database import Base


class SeverityEnum(str, enum.Enum):
    LOW = "P4"
    MEDIUM = "P3"
    HIGH = "P2"
    CRITICAL = "P1"


class IncidentStatusEnum(str, enum.Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    MITIGATED = "MITIGATED"
    RESOLVED = "RESOLVED"


class Incident(Base):
    __tablename__ = "incidents"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    severity: Mapped[SeverityEnum] = mapped_column(
        SQLEnum(SeverityEnum), default=SeverityEnum.MEDIUM, nullable=False
    )
    status: Mapped[IncidentStatusEnum] = mapped_column(
        SQLEnum(IncidentStatusEnum), default=IncidentStatusEnum.OPEN, nullable=False
    )
    
    # 384-dimensional vector embedding stored directly in Postgres via pgvector
    embedding: Mapped[Optional[List[float]]] = mapped_column(Vector(384), nullable=True)
    
    # Root Cause Analysis generated by AI Agent
    ai_rca_summary: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    suggested_remediation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    metadata_json: Mapped[dict] = mapped_column(JSONB, server_default=text("'{}'::jsonb"), nullable=False)
    
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # One-to-Many Relationship: An Incident can aggregate multiple deduplicated Alerts
    alerts: Mapped[List["Alert"]] = relationship("Alert", back_populates="incident")


class Alert(Base):
    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    service_name: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    environment: Mapped[str] = mapped_column(String(50), default="production", nullable=False)
    error_message: Mapped[str] = mapped_column(Text, nullable=False)
    stack_trace: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    
    # SHA-256 fingerprint generated from (service_name + stack_trace) for instant deduplication
    fingerprint: Mapped[str] = mapped_column(String(64), index=True, nullable=False)
    
    # Foreign Key pointing to the parent Incident once grouped
    incident_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True), ForeignKey("incidents.id", ondelete="SET NULL"), nullable=True
    )
    
    payload: Mapped[dict] = mapped_column(JSONB, server_default=text("'{}'::jsonb"), nullable=False)
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    incident: Mapped[Optional["Incident"]] = relationship("Incident", back_populates="alerts")


# Database Indexing
# 1. HNSW Index for ultra-fast vector similarity search
Index(
    "idx_incident_embedding",
    Incident.embedding,
    postgresql_using="hnsw",
    postgresql_with={"m": 16, "ef_construction": 64},
    postgresql_ops={"embedding": "vector_cosine_ops"}
)

# 2. Time-series Descending Index for fast alert log lookups
Index("idx_alert_received_at", Alert.received_at.desc())